---
name: "Bug report"
about: "Create a report to help us improve"
title: "Bug"
labels:
  - bug
assignees:
  - Redume
body:
  - type: markdown
    attributes:
      value: |
        ## If there is not enough information, the issue will probably be ignored
  - type: input
    id: os
    attributes:
      label: Name distribution/os
      description: Write the name of the distribution/os
      placeholder: Windows 11
    validations:
      required: true
  - type: input
    id: graphical
    attributes:
      label: Name graphical shell
      description: Write the name system graphical shell
      placeholder: GNOME 42
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browsers are you seeing the problem on
      multiple: true
      options:
        - Firefox, Tor
        - Chrome, Vivaldi, Brave
        - Edge
        - Chromium
  - type: textarea
    id: problem
    attributes:
      label: Detailed description of the problem
      description: Describe the minimum actions to be taken
